nodeLinker: node-modules

# Enable zero-installs (optional)
# enableGlobalCache: false

# Compression for cached packages
compressionLevel: mixed

# Network settings
httpTimeout: 60000
networkConcurrency: 8
# Plugin support (optional)
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#     spec: "@yarnpkg/plugin-workspace-tools"
