# Generated by Django 5.1.5 on 2025-11-07 23:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('description_stripped', models.TextField(blank=True)),
                ('content', models.JSONField(default=dict)),
                ('content_html', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('icon_prop', models.JSONField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('access', models.IntegerField(choices=[(0, 'Private'), (1, 'Project'), (2, 'Workspace')], default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('sort_order', models.FloatField(default=65535)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('public_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('view_count', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_pages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='projects.project')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_pages', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PageActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('published', 'Published'), ('archived', 'Archived'), ('commented', 'Commented')], max_length=20)),
                ('field', models.CharField(blank=True, max_length=255)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_activities', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pages.page')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'page_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.JSONField(default=dict)),
                ('comment_html', models.TextField(blank=True)),
                ('comment_stripped', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pages.pagecomment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'page_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_reactions', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='pages.pagecomment')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='pages.page')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'page_reactions',
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('content', models.JSONField(default=dict)),
                ('content_html', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_versions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pages.page')),
            ],
            options={
                'db_table': 'page_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['workspace', 'project', 'deleted_at'], name='pages_workspa_5a13ad_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['parent', 'sort_order'], name='pages_parent__98056d_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_published', 'public_slug'], name='pages_is_publ_fa7b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='pages_search__f65627_gin'),
        ),
        migrations.AddIndex(
            model_name='pageactivity',
            index=models.Index(fields=['page', '-created_at'], name='page_activi_page_id_52786c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomment',
            index=models.Index(fields=['page', 'created_at'], name='page_commen_page_id_612f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='pagereaction',
            index=models.Index(fields=['page', 'actor'], name='page_reacti_page_id_9fcc24_idx'),
        ),
        migrations.AddIndex(
            model_name='pagereaction',
            index=models.Index(fields=['comment', 'actor'], name='page_reacti_comment_91da2d_idx'),
        ),
        migrations.AddIndex(
            model_name='pageversion',
            index=models.Index(fields=['page', '-version_number'], name='page_versio_page_id_ca3741_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageversion',
            unique_together={('page', 'version_number')},
        ),
    ]
