# Generated by Django 5.1.5 on 2025-11-07 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'page_favorites',
                'indexes': [models.Index(fields=['user', 'created_at'], name='page_favori_user_id_434df5_idx')],
                'unique_together': {('page', 'user')},
            },
        ),
    ]
