# Generated by Django 5.1.5 on 2025-11-07 23:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('icon_prop', models.JSONField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('network', models.IntegerField(choices=[(0, 'Private'), (1, 'Internal'), (2, 'Public')], default=1)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('page_view', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(20, 'Admin'), (10, 'Member'), (5, 'Viewer')], default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
            ],
            options={
                'db_table': 'project_members',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'archived_at'], name='projects_workspa_6d623f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('workspace', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'member')},
        ),
    ]
